// frontend-vue3/src/components/AppSelect.vue
<script setup lang="ts">
import Select from "@/components/ui/Select.vue";
import SelectTrigger from "@/components/ui/SelectTrigger.vue";
import SelectValue from "@/components/ui/SelectValue.vue";
import SelectContent from "@/components/ui/SelectContent.vue";
import SelectItem from "@/components/ui/SelectItem.vue";
import type { SelectOption } from "@/types";

const emptySelectValue = "__datus_empty__";

function toSelectValue(value: string) {
  return value || emptySelectValue;
}

function fromSelectValue(value: string) {
  return value === emptySelectValue ? "" : value;
}

const props = withDefaults(defineProps<{
  value: string;
  options: SelectOption[];
  disabled?: boolean;
  placeholder?: string;
}>(), {
  placeholder: "请选择"
});

const emit = defineEmits<{
  "update:value": [value: string];
}>();
</script>

<template>
  <Select :value="toSelectValue(value)" :disabled="disabled" @update:value="(v) => emit('update:value', fromSelectValue(v))">
    <SelectTrigger class="appSelectTrigger" :aria-label="placeholder">
      <SelectValue :placeholder="placeholder" />
    </SelectTrigger>
    <SelectContent class="appSelectContent" position="popper" :side-offset="6">
      <SelectItem
        v-for="option in options"
        :key="`${option.value}-${option.label}`"
        class="appSelectItem"
        :value="toSelectValue(option.value)"
      >
        {{ option.label }}
      </SelectItem>
    </SelectContent>
  </Select>
</template>

// frontend/src/components/app-select.tsx
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { SelectOption } from "@/types";

const emptySelectValue = "__datus_empty__";

function toSelectValue(value: string) {
  return value || emptySelectValue;
}

function fromSelectValue(value: string) {
  return value === emptySelectValue ? "" : value;
}

export function AppSelect({
  value,
  onChange,
  options,
  disabled,
  placeholder = "请选择"
}: {
  value: string;
  onChange: (value: string) => void;
  options: SelectOption[];
  disabled?: boolean;
  placeholder?: string;
}) {
  return (
    <Select value={toSelectValue(value)} onValueChange={(next) => onChange(fromSelectValue(next))} disabled={disabled}>
      <SelectTrigger className="appSelectTrigger" aria-label={placeholder}>
        <SelectValue placeholder={placeholder} />
      </SelectTrigger>
      <SelectContent className="appSelectContent" position="popper" sideOffset={6}>
        {options.map((option) => (
          <SelectItem className="appSelectItem" key={`${option.value}-${option.label}`} value={toSelectValue(option.value)}>
            {option.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}
