// frontend-vue3/src/components/chat/MessageContent.vue
<script setup lang="ts">
import MarkdownIt from "markdown-it";
import { chatApi } from "@/lib/api";
import { useConnection } from "@/composables/useConnection";

import type { ChatMessage } from "@/types";
import ToolCard from "./ToolCard.vue";
import FeedbackButtons from "./FeedbackButtons.vue";
import SuccessStoryButton from "./SuccessStoryButton.vue";

const md = new MarkdownIt({
  html: false,
  linkify: true,
  typographer: true,
  breaks: true,
});

md.enable("table");
md.enable("strikethrough");

const defaultRender =
  md.renderer.rules.link_open ||
  function (tokens, idx, options, _env, self) {
    return self.renderToken(tokens, idx, options);
  };
md.renderer.rules.link_open = function (tokens, idx, options, env, self) {
  tokens[idx].attrSet("target", "_blank");
  tokens[idx].attrSet("rel", "noreferrer");
  return defaultRender(tokens, idx, options, env, self);
};

const props = defineProps<{
  message: ChatMessage;
  sessionId?: string;
}>();

const blocks = props.message.blocks?.length
  ? props.message.blocks
  : [{ type: "markdown" as const, content: props.message.content }];

function renderMarkdown(content: string): string {
  return md.render(content);
}

async function handleFeedback(emoji: string) {
  if (!props.sessionId) return;
  const { effectiveBase } = useConnection();
  const base = effectiveBase();
  try {
    await chatApi.feedback(base, {
      source_session_id: props.sessionId,
      reaction_emoji: emoji,
      reference_msg: props.message.content.slice(0, 2000),
    });
  } catch (error) {
    console.error("Feedback failed:", error);
  }
}
</script>

<template>
  <div class="messageBlocks">
    <template v-for="(block, index) in blocks" :key="index">
      <ToolCard
        v-if="block.type === 'tool-call'"
        mode="call"
        :tool-name="block.toolName"
        :value="block.params"
      />
      <ToolCard
        v-else-if="block.type === 'tool-result'"
        mode="result"
        :tool-name="block.toolName"
        :value="block.result"
        :duration="block.duration"
        :short-desc="block.shortDesc"
      />
      <div v-else class="markdownBody" v-html="renderMarkdown(block.content)" />
    </template>
    <div v-if="message.role === 'assistant' && sessionId" class="messageActions">
      <FeedbackButtons
        :session-id="sessionId"
        :message-content="message.content"
        @feedback="handleFeedback"
      />
      <SuccessStoryButton
        :session-id="sessionId"
        :message-content="message.content"
      />
    </div>
  </div>
</template>

// frontend/src/components/chat/message-content.tsx
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import type { ChatMessage } from "@/types";

import { ToolCard } from "./tool-card";

function MarkdownMessage({ content }: { content: string }) {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        a: ({ children, ...props }) => (
          <a {...props} target="_blank" rel="noreferrer">
            {children}
          </a>
        )
      }}
    >
      {content}
    </ReactMarkdown>
  );
}

export function MessageContent({ message }: { message: ChatMessage }) {
  const blocks = message.blocks?.length ? message.blocks : [{ type: "markdown" as const, content: message.content }];
  return (
    <div className="messageBlocks">
      {blocks.map((block, index) => {
        if (block.type === "tool-call") {
          return <ToolCard key={index} mode="call" toolName={block.toolName} value={block.params} />;
        }
        if (block.type === "tool-result") {
          return (
            <ToolCard
              key={index}
              mode="result"
              toolName={block.toolName}
              value={block.result}
              duration={block.duration}
              shortDesc={block.shortDesc}
            />
          );
        }
        return (
          <div className="markdownBody" key={index}>
            <MarkdownMessage content={block.content} />
          </div>
        );
      })}
    </div>
  );
}
