// frontend/src/components/error-boundary.tsx
import { Component } from "react";

interface ErrorBoundaryState {
  hasError: boolean;
}

export class ErrorBoundary extends Component<{ children: React.ReactNode; fallback?: React.ReactNode }, ErrorBoundaryState> {
  constructor(props: { children: React.ReactNode; fallback?: React.ReactNode }) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(): ErrorBoundaryState {
    return { hasError: true };
  }

  componentDidCatch(error: Error, info: React.ErrorInfo) {
    console.error("ErrorBoundary caught:", error, info);
  }

  render() {
    if (this.state.hasError) {
      return (
        this.props.fallback ?? (
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              height: "100dvh",
              padding: 24,
              color: "var(--text-muted)",
              fontSize: 14
            }}
          >
            <div style={{ textAlign: "center" }}>
              <p>Something went wrong.</p>
              <button
                type="button"
                onClick={() => {
                  this.setState({ hasError: false });
                  window.location.reload();
                }}
                style={{
                  marginTop: 8,
                  padding: "6px 16px",
                  border: "1px solid var(--line)",
                  borderRadius: 8,
                  background: "var(--surface)",
                  color: "var(--text)",
                  cursor: "pointer"
                }}
              >
                Reload
              </button>
            </div>
          </div>
        )
      );
    }
    return this.props.children;
  }
}

// frontend-vue3/src/components/ErrorBoundary.vue
<script setup lang="ts">
import { ref, onErrorCaptured } from "vue";

const props = withDefaults(defineProps<{
  fallbackText?: string;
}>(), {
  fallbackText: ""
});

const hasError = ref(false);
const errorMessage = ref("");

onErrorCaptured((err) => {
  hasError.value = true;
  errorMessage.value = err.message;
  console.error("ErrorBoundary caught:", err);
  return false; // Prevent propagation
});

const reset = () => {
  hasError.value = false;
  errorMessage.value = "";
};
</script>

<template>
  <div v-if="hasError" class="markdownBody">
    <p v-if="fallbackText">{{ fallbackText }}</p>
    <p v-else>Something went wrong.</p>
    <button type="button" @click="reset" style="margin-top: 8px; padding: 4px 12px; border: 1px solid var(--line); border-radius: 6px; background: var(--surface); color: var(--text); cursor: pointer; font-size: 12px;">
      重试
    </button>
  </div>
  <slot v-else />
</template>
